In [1]:
# 필요한 패키지 import
import pandas as pd
import numpy as np

import platform
import matplotlib.pyplot as plt

%matplotlib inline

path = "c:/Windows/Fonts/malgun.ttf"
from matplotlib import font_manager, rc
if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system... sorry~~~~')    

plt.rcParams['axes.unicode_minus'] = False

from bs4 import BeautifulSoup 
from urllib.request import urlopen
import urllib
import time

In [3]:
tmp1 = 'http://www.econovill.com/news/articleView.html?idxno=222104'

response = urlopen(tmp1.format())

soup = BeautifulSoup(response, "html.parser")

soup

<!DOCTYPE html>

<html lang="ko">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="width=1420" name="viewport"/>
<meta content="WhdDrvJkircBmG5fJbtCNwvyqbHKaAkUFRwx6tNjwcw" name="google-site-verification">
<meta content="130190110425670" property="fb:pages"/>
<meta content="682133611886145" property="fb:pages"/>
<meta content="458228490867173" property="fb:app_id"/>
<meta content="article" property="og:type"/>
<meta content="ko_KR" property="og:locale"/>
<meta content="단통법 논란, “정부와 국회는 그 입 다물라”" property="og:title"/>
<meta content="http://www.econovill.com/news/articleView.html?idxno=222104" property="og:url"/>
<meta content="http://www.econovill.com/news/photo/201410/222104_6448_492.jpg" property="og:image"/>
<meta content="http://www.econovill.com/news/thumbnail/201410/222104_6448_492_v150.jpg" property="dable:image"/>
<link href="http://www.econovill.com/news/photo/201410/222104

In [6]:
# 검색된 text를 리스트 안에 넣어준다.
tmp_list = []
tmp_list.append(soup)
    
tmp_list

[<!DOCTYPE html>
 
 <html lang="ko">
 <head>
 <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
 <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
 <meta content="width=1420" name="viewport"/>
 <meta content="WhdDrvJkircBmG5fJbtCNwvyqbHKaAkUFRwx6tNjwcw" name="google-site-verification">
 <meta content="130190110425670" property="fb:pages"/>
 <meta content="682133611886145" property="fb:pages"/>
 <meta content="458228490867173" property="fb:app_id"/>
 <meta content="article" property="og:type"/>
 <meta content="ko_KR" property="og:locale"/>
 <meta content="단통법 논란, “정부와 국회는 그 입 다물라”" property="og:title"/>
 <meta content="http://www.econovill.com/news/articleView.html?idxno=222104" property="og:url"/>
 <meta content="http://www.econovill.com/news/photo/201410/222104_6448_492.jpg" property="og:image"/>
 <meta content="http://www.econovill.com/news/thumbnail/201410/222104_6448_492_v150.jpg" property="dable:image"/>
 <link href="http://www.econovill.com/news/p

In [7]:
import pandas as pd
pd.options.mode.chained_assignment = None
 
import numpy as np
np.random.seed(0)
 
from konlpy.tag import Twitter
twitter = Twitter()
 
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
 
# tokenizer : 문장에서 색인어 추출을 위해 명사,동사,알파벳,숫자 정도의 단어만 뽑아서 
# normalization, stemming 처리하도록 함
def tokenizer(raw, pos=["Noun","Alpha","Verb","Number"], stopword=[]):
    return [
        word for word, tag in twitter.pos(
            raw, 
            norm=True,   # normalize 그랰ㅋㅋ -> 그래ㅋㅋ
            stem=True    # stemming 바뀌나->바뀌다
            )
            if len(word) > 1 and tag in pos and word not in stopword
        ]
 
# 테스트 문장
rawdata = [
    '남북 고위급회담 대표단 확정..남북 해빙모드 급물살',
    '[남북 고위급 회담]장차관만 6명..판 커지는 올림픽 회담',
    
    '문재인 대통령과 대통령의 영부인 김정숙여사 내외의 동반 1987 관람 후 인터뷰',
    '1987 본 문 대통령.."그런다고 바뀌나? 함께 하면 바뀐다"',
    
    '이명박 전 대통령과 전 대통령의 부인 김윤옥 여사, 그리고 전 대통령의 아들 이시형씨의 동반 검찰출석이 기대됨'
]
 

C:\Users\hys55\AppData\Local\Continuum\anaconda3\lib\site-packages\konlpy\tag\_okt.py:16: UserWarning: "Twitter" has changed to "Okt" since KoNLPy v0.4.5.
  warn('"Twitter" has changed to "Okt" since KoNLPy v0.4.5.')
C:\Users\hys55\AppData\Local\Continuum\anaconda3\lib\site-packages\jpype\_core.py:210: UserWarning: 
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------

  """)


In [8]:
vectorize = CountVectorizer(
    tokenizer = tokenizer,
    min_df =2)   ### mid_df = 2 이면 문서에 2개 미만으로 나타나는 단어 무시

X = vectorize.fit_transform(rawdata)

print(
    'fit_transform, (sentence {}, feature {})'.format(X.shape[0], X.shape[1])
)

print(type(X))

print(X.toarray())

features = vectorize.get_feature_names()

fit_transform, (sentence 5, feature 7)
<class 'scipy.sparse.csr.csr_matrix'>
[[0 1 2 0 0 0 1]
 [0 1 1 0 0 0 2]
 [1 0 0 2 1 1 0]
 [1 0 0 1 0 0 0]
 [0 0 0 3 1 1 0]]


In [9]:
# 검색 문장에서 feature 를 뽑아냄
srch = [t for t in tokenizer('1987 관람한 대통령') if t in features]
print(srch)

srch_dtm = np.asarray(X.toarray())[:, [
    
    vectorize.vocabulary_get(i) for i in srch
]]

['1987', '대통령']


AttributeError: 'CountVectorizer' object has no attribute 'vocabulary_get'

In [ ]:
score = srch_dtm.sum(axis =1)
print(score)

for i in score.argsort()[::-1]:
    if score[i]>0:
        print('{} / score : {}'.format(rawdata[i], score[i]))

In [ ]:
#### - TfidfVectorizer()

* 문서목록에서 각 문서의 feature를 tf-idf 값을 가중치로 설정한 BOW 벡터를 만든다.

In [ ]:
vectorize = TfidVectorizer(
    tokenizer = tokenizer,
    min_df = 2,
    
    sublinear_tf = True

)
X = vectorize.fit_transform(rawdata)

print(
    'fit_transform, (sentence {}, feature {})'.format(X.shape[0], X.shape[1])
)

print(X.toarray())

features = vectorize.get_feature_names()

In [ ]:
# CounterVector()에서 유사문장을 뽑아낸 방법을 동일하게
# TfidVector()에 적용
# 검색 문장에서 feature를 뽑아냄
srch=[t for t in tokenizer('1987 관람한 대통령 인터뷰 기사') if t in features]
print(srch)
# ['1987', '대통령']
 
# dtm 에서 검색하고자 하는 feature만 뽑아낸다.
srch_dtm = np.asarray(X.toarray())[:, [
  
    # vectorize.vocabulary_.get 는 특정 feature 가 dtm 에서 가지고 있는 index값을 리턴한다
    vectorize.vocabulary_.get(i) for i in srch
]]
 
#       1987    대통령
# 0     0.000000    0.000000
# 1     0.000000    0.000000
# 2     0.416804    0.691970
# 3     0.769447    0.638711
# 4     0.000000    0.869563
 
score = srch_dtm.sum(axis=1)
print(score)
# array([0.         0.         1.10877443 1.40815765 0.8695635 ], dtype=int64) 문장별 feature 합계 점수
 
for i in score.argsort()[::-1]:
    if score[i] > 0:
        print('{} / score : {}'.format(rawdata[i], score[i]))
 
# 1987 본 문 대통령.."그런다고 바뀌나? 함께 하면 바뀐다" / score : 1.408157650537996
# 문재인 대통령과 대통령의 영부인 김정숙여사 내외의 동반 1987 관람 후 인터뷰 / score : 1.1087744279177436
# 이명박 전 대통령과 전 대통령의 부인 김윤옥 여사, 그리고 전 대통령의 아들 이시형씨의 동반 검찰출석이 기대됨 / score : 0.869563495264799
 

In [10]:
# search 문장 벡터
srch_vector = vectorize.transform([
    '1987 관람한 대통령 인터뷰 기사'
])
 
print(srch_vector.shape)
# (1, 7)
 

(1, 7)


In [11]:
from sklearn.metrics.pairwise import linear_kernel
 
# linear_kernel는 두 벡터의 dot product 이다.
cosine_similar = linear_kernel(srch_vector, X).flatten()
# cosine_similar = (srch_vector*X.T).toarray().flatten()
 
print(cosine_similar)
# [0.         0.         0.62017367 0.31622777 0.3]
 
print(cosine_similar.shape)
# (5,)
 
# 유사한 rawdata index
sim_rank_idx = cosine_similar.argsort()[::-1]
print(sim_rank_idx)
#[2 3 4 1 0]
 
for i in sim_rank_idx:
    if cosine_similar[i] > 0:
        print('{} / score : {}'.format(rawdata[i], cosine_similar[i]))
 
# 문재인 대통령과 대통령의 영부인 김정숙여사 내외의 동반 1987 관람 후 인터뷰 / score : 0.6201736729460423
# 1987 본 문 대통령.."그런다고 바뀌나? 함께 하면 바뀐다" / score : 0.3162277660168379
# 이명박 전 대통령과 전 대통령의 부인 김윤옥 여사, 그리고 전 대통령의 아들 이시형씨의 동반 검찰출석이 기대됨 / score : 0.3
 

[0. 0. 3. 2. 3.]
(5,)
[4 2 3 1 0]
이명박 전 대통령과 전 대통령의 부인 김윤옥 여사, 그리고 전 대통령의 아들 이시형씨의 동반 검찰출석이 기대됨 / score : 3.0
문재인 대통령과 대통령의 영부인 김정숙여사 내외의 동반 1987 관람 후 인터뷰 / score : 3.0
1987 본 문 대통령.."그런다고 바뀌나? 함께 하면 바뀐다" / score : 2.0
